### ISSUE TITLE
Travis is complaining during spec tests about the way the Apt class is being called.

### ISSUE THREAD

**Issue by nrvale0** [Nextdoor/puppet_rightscale#15]
I've not tried to track it down but it looks to be related to the way the fixtures .pp files are calling class '::apt' expecting an interface other than the one presented by puppetlabs-apt.

**Comment by diranged** [comment]
@nrvale0 it looks like the issue is probably that the `apt` repo is not pinned to a particular revision here: https://github.com/Nextdoor/puppet_rightscale/blob/master/.fixtures.yml#L3.

Try adding some pinning (try the version our internal repos use) and see if that fixes it.

**Comment by nrvale0** [comment]
fixed
