### ISSUE TITLE
Reset the ruby-rest-client version to 'installed' by default

### ISSUE THREAD

**Issue by diranged** [Nextdoor/puppet_rightscale#19]
Commit f114e0f5819d6bf11d30676218c279445f864463 broke the install of the `ruby-rest-client` package by hard-coding the default version to `1.6.7-1` rather than leaving it as `installed`. Please revert this change @nrvale0.

**Comment by nrvale0** [comment]
1.6.7-1 is the minimal version of the package which will work on Ubuntu 12.04. The previous value, 1.6.7, would result in a failure to install the deb at all as it was not a valid package version.

Setting to 'installed' and users are on their own to ensure the correct package version.

We could add a class parameter to allow spec of package version but that would involved a rev to the class API which then requires rev of the SemVer to 2.x.x. Will create  a ticket for that...it, in the end, is the correct behavior anyway.
